export const FETCH_NEWS_PENDING = 'FETCH_NEWS_PENDING';
export const FETCH_NEWS_FULFILLED = 'FETCH_NEWS_FULFILLED';
export const FETCH_NEWS_REJECTED = 'FETCH_NEWS_REJECTED';

export const FETCH_NEW_PENDING = 'FETCH_NEW_PENDING';
export const FETCH_NEW_FULFILLED = 'FETCH_NEW_FULFILLED';
export const FETCH_NEW_REJECTED = 'FETCH_NEW_REJECTED';
